server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: menu-service
              uri: lb://MENU-SERVICE
              predicates:
                - Path=/api/platos/**

            - id: pedidos-service
              uri: lb://PEDIDOS-SERVICE
              predicates:
                - Path=/api/pedidos/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true