CREATE TABLE IF NOT EXISTS pedidos (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    plato_id BIGINT NOT NULL,
    cantidad INT NOT NULL,
    mesa INT NOT NULL,
    estado VARCHAR(50) NOT NULL DEFAULT 'PENDIENTE'
);